export type DomainErrorCode =
  | 'APPOINTMENT_NOT_CONFIRMABLE'
  | 'APPOINTMENT_NOT_CANCELLABLE'
  | 'APPOINTMENT_NOT_FOUND'
  | 'BOOKING_KIND_MISMATCH'
  | 'CANCELLATION_WINDOW_CLOSED'
  | 'COMPLETION_NOT_AUTHORIZED'
  | 'DUPLICATE_ACTIVE_BOOKING'
  | 'IDEMPOTENCY_KEY_REUSED'
  | 'INVALID_ASSIGNMENT'
  | 'INVALID_TIMESTAMP'
  | 'INVALID_VALUE'
  | 'PATIENT_BOOKING_GUARD_MISMATCH'
  | 'PAYROLL_DUPLICATE_CREDIT'
  | 'PAYROLL_NOT_ELIGIBLE'
  | 'PAYROLL_PERIOD_ALREADY_CLOSED'
  | 'PAYROLL_PERIOD_NOT_CLOSED'
  | 'BLOCKED_TIME_OFF_GRID'
  | 'FOLLOW_UP_DAY_CLOSED'
  | 'FOLLOW_UP_NOT_DECIDABLE'
  | 'FOLLOW_UP_TIME_OFF_GRID'
  | 'SCHEDULE_EXCEPTION_DUPLICATED'
  | 'SCHEDULE_INTERVALS_OVERLAP'
  | 'SCHEDULE_ORPHANS_APPOINTMENTS'
  | 'SCHEDULE_VERSION_CONFLICT'
  | 'SCHEDULE_WEEKDAY_DUPLICATED'
  | 'SLOT_NOT_FOUND'
  | 'SLOT_UNAVAILABLE'
  | 'TRANSITION_NOT_ALLOWED';

export class DomainError extends Error {
  public readonly name = 'DomainError';

  public constructor(
    public readonly code: DomainErrorCode,
    message: string
  ) {
    super(message);
  }
}
