export const BUSINESS_DELIVERY_APPLICATION = Symbol(
  'BUSINESS_DELIVERY_APPLICATION'
);
export const BUSINESS_EXPORT_APPLICATION = Symbol(
  'BUSINESS_EXPORT_APPLICATION'
);
export const BUSINESS_RETENTION_APPLICATION = Symbol(
  'BUSINESS_RETENTION_APPLICATION'
);
