export const CALENDAR_PILOT_APPLICATION = Symbol('CALENDAR_PILOT_APPLICATION');
export const CALENDAR_PILOT_REPOSITORY = Symbol('CALENDAR_PILOT_REPOSITORY');
export const CALENDAR_PILOT_SESSIONS = Symbol('CALENDAR_PILOT_SESSIONS');
